DROP TABLE IF EXISTS payment_callback_events;
DROP TABLE IF EXISTS supply_usage_records;
DROP TABLE IF EXISTS wallet_reservations;
DROP TABLE IF EXISTS supply_channel_endpoints;
DROP TABLE IF EXISTS virtual_keys;
DROP TRIGGER IF EXISTS wallet_entries_balance_check ON wallet_entries;
DROP TRIGGER IF EXISTS wallet_journals_balance_check ON wallet_journals;
DROP FUNCTION IF EXISTS e2m_validate_wallet_journal_balance();
DROP FUNCTION IF EXISTS e2m_assert_wallet_journal_balance(TEXT);
DROP TABLE IF EXISTS wallet_entries;
DROP TABLE IF EXISTS wallet_journals;
DROP TABLE IF EXISTS wallet_accounts;
DROP TABLE IF EXISTS hybrid_allocations;
DROP INDEX IF EXISTS uq_payment_orders_provider_order;
ALTER TABLE payment_orders DROP COLUMN IF EXISTS provider_order_id;
ALTER TABLE upstream_pools DROP CONSTRAINT IF EXISTS ck_upstream_pools_resource_class;
ALTER TABLE upstream_pools DROP CONSTRAINT IF EXISTS ck_upstream_pools_delivery_mode;
ALTER TABLE upstream_pools DROP COLUMN IF EXISTS delivery_mode;
ALTER TABLE upstream_pools DROP COLUMN IF EXISTS resource_class;
